#ifndef RA_BAREMETAL_TILE_VIEW_H
#define RA_BAREMETAL_TILE_VIEW_H

// The tile layout of the ROM browser: one square picture per game with its
// name below. Draws into an RGB565 pixel buffer and does not use Circle, so
// tests/tile-preview.mjs can render the same screens on a PC.

#include <stddef.h>
#include <stdint.h>

#include <circle/font.h>

#define TILE_RGB565(r, g, b) ((uint16_t)((((r) >> 3) << 11) | (((g) >> 2) << 5) | ((b) >> 3)))

struct TileSurface
{
	uint16_t *pixels;
	unsigned width;
	unsigned height;
	unsigned pitch;		// pixels per line
};

struct TileLayout
{
	unsigned columns;
	unsigned rows;
	unsigned tileSize;	// square picture, pixels
	unsigned gapX;
	unsigned rowHeight;	// picture, caption and gap
	unsigned headerHeight;
	unsigned footerHeight;
	unsigned gridY;
	const TFont *pTitleFont;
	const TFont *pTextFont;		// header and footer
	const TFont *pCaptionFont;	// names below the tiles
};

struct TileEntry
{
	const char *name;	// file or folder name
	const char *system;	// "NES", "GBA", ... ("" for folders)
	bool isDirectory;
	const uint16_t *pPicture;	// tileSize x tileSize, 0 while not loaded
};

TileLayout ComputeTileLayout(unsigned screenWidth, unsigned screenHeight);

// First grid row to show so that the selected entry is visible.
unsigned TileFirstRow(const TileLayout &layout, unsigned selected, unsigned firstRow);

void DrawTileBrowser(const TileSurface &surface, const TileLayout &layout,
		     const char *pTitle, const char *pDirectory,
		     const TileEntry *pEntries, unsigned count,
		     unsigned selected, unsigned firstRow);

void DrawTileLaunch(const TileSurface &surface, const TileLayout &layout,
		    const TileEntry &entry, const char *pCoreName);

// Square tile pictures (tileSize x tileSize RGB565). The picture is scaled to
// fit and centred on the tile background; returns false if the data is not
// a usable PNG.
bool MakeTilePictureFromPng(const uint8_t *pData, size_t size, unsigned tileSize, uint16_t *pTile);
void MakeTilePictureFromRgb565(const uint16_t *pPixels, unsigned width, unsigned height,
			       unsigned tileSize, uint16_t *pTile);

// System pictures built into the kernel from baremetal/assets/systems
// (generated by baremetal/splash.mjs into gen/system_images.c).
struct TSystemImage
{
	const char *system;
	unsigned width;
	unsigned height;
	const uint16_t *pixels;
};
extern "C" const TSystemImage g_SystemImages[];
extern "C" const unsigned g_SystemImageCount;

const TSystemImage *FindSystemImage(const char *pSystem);

#endif
